name: Fetch TED data and update site

on:
  schedule:
    - cron: "15 20 * * *"   # kör 20:15 UTC
  workflow_dispatch:      # tillåt manuell körning

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Fetch Swedish TED notices
        run: |
          python scripts/fetch_ted.py --country SE --days 7 --max 300 --out data/ted.json

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ted.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update TED data $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
