name: Test TED fetch

on:
  workflow_dispatch:  # körs bara manuellt

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python scripts/fetch_ted.py
