name: Fetch TED data and update site

on:
  schedule:
    - cron: "10 6 * * *"   # dagligen 06:10 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Fetch Swedish TED notices
        run: python scripts/fetch_ted.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ted.json
          git diff --quiet && echo "No changes" || (git commit -m "Update TED data" && git push)
